"""Firestore tenant veri katmani."""

from .bootstrap import firebase_enabled, init_firebase
from .schema import (
    CUSTOMERS_COLLECTION,
    DOC_CURRENT,
    DOC_DEFAULTS,
    PLATFORM_COLLECTION,
    SUBCOL_SETTINGS,
    TENANTS_COLLECTION,
    TENANT_INDEX_COLLECTION,
)
from .serialization import serialize_model_row, serialize_value
from .tenant_repository import (
    batch_upsert_analysis,
    batch_upsert_collection,
    batch_upsert_orders,
    batch_upsert_positions,
    batch_upsert_signals,
    batch_upsert_symbol_rules,
    batch_upsert_trades,
    delete_tenant_subcollection,
    get_customer,
    get_platform_defaults,
    get_tenant_runtime,
    get_tenant_settings,
    list_tenant_admin_ids,
    mark_tenant_migrated,
    update_customer_bot_settings,
    update_customer_connections,
    upsert_customer,
    upsert_platform_defaults,
    upsert_tenant_entity,
    upsert_tenant_runtime,
    upsert_tenant_settings,
)

__all__ = [
    "CUSTOMERS_COLLECTION",
    "DOC_CURRENT",
    "DOC_DEFAULTS",
    "PLATFORM_COLLECTION",
    "SUBCOL_SETTINGS",
    "TENANTS_COLLECTION",
    "TENANT_INDEX_COLLECTION",
    "batch_upsert_analysis",
    "batch_upsert_collection",
    "batch_upsert_orders",
    "batch_upsert_positions",
    "batch_upsert_signals",
    "batch_upsert_symbol_rules",
    "batch_upsert_trades",
    "delete_tenant_subcollection",
    "firebase_enabled",
    "get_customer",
    "get_platform_defaults",
    "get_tenant_runtime",
    "get_tenant_settings",
    "init_firebase",
    "list_tenant_admin_ids",
    "mark_tenant_migrated",
    "serialize_model_row",
    "serialize_value",
    "update_customer_bot_settings",
    "update_customer_connections",
    "upsert_customer",
    "upsert_platform_defaults",
    "upsert_tenant_entity",
    "upsert_tenant_runtime",
    "upsert_tenant_settings",
]
