"""initial schema

Revision ID: 587112aae608
Revises: 
Create Date: 2026-07-10 16:33:52.968404

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '587112aae608'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_sessions'))
    )
    op.create_index(op.f('ix_admin_sessions_admin_id'), 'admin_sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_sessions_token_hash'), 'admin_sessions', ['token_hash'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('live_trading_ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('algo_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=24), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('working_type', sa.String(length=16), nullable=False),
    sa.Column('close_position', sa.Boolean(), nullable=False),
    sa.Column('client_algo_id', sa.String(length=36), nullable=False),
    sa.Column('binance_order_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_algo_orders'))
    )
    op.create_index(op.f('ix_algo_orders_binance_order_id'), 'algo_orders', ['binance_order_id'], unique=False)
    op.create_index(op.f('ix_algo_orders_client_algo_id'), 'algo_orders', ['client_algo_id'], unique=True)
    op.create_index(op.f('ix_algo_orders_position_id'), 'algo_orders', ['position_id'], unique=False)
    op.create_index(op.f('ix_algo_orders_status'), 'algo_orders', ['status'], unique=False)
    op.create_index(op.f('ix_algo_orders_symbol'), 'algo_orders', ['symbol'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('ema_fast', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('ema_mid', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('ema_slow', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('rsi_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('atr_value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('current_volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_volume_20', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume_24h_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('spread_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('funding_rate_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('open_interest', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('trend_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ema_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rsi_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volatility_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('spread_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('funding_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('open_interest_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('suggested_side', sa.String(length=8), nullable=True),
    sa.Column('decision', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results'))
    )
    op.create_index(op.f('ix_analysis_results_analyzed_at'), 'analysis_results', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_symbol'), 'analysis_results', ['symbol'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_table('binance_connection_status',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('account_access_ok', sa.Boolean(), nullable=False),
    sa.Column('futures_account_usable', sa.Boolean(), nullable=False),
    sa.Column('trading_permission_ok', sa.Boolean(), nullable=False),
    sa.Column('position_mode_verified', sa.Boolean(), nullable=False),
    sa.Column('multi_assets_mode_off_verified', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_binance_connection_status'))
    )
    op.create_table('bot_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('bot_mode', sa.String(length=16), nullable=True),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_events'))
    )
    op.create_index(op.f('ix_bot_events_event_type'), 'bot_events', ['event_type'], unique=False)
    op.create_table('bot_runtime_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_state', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_mode_reason', sa.String(length=512), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.String(length=1024), nullable=True),
    sa.Column('worker_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_runtime_status'))
    )
    op.create_table('bot_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('live_trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('bot_enabled', sa.Boolean(), nullable=False),
    sa.Column('margin_per_trade_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('max_allowed_leverage', sa.Integer(), nullable=False),
    sa.Column('margin_type', sa.String(length=16), nullable=False),
    sa.Column('position_mode', sa.String(length=16), nullable=False),
    sa.Column('multi_assets_mode', sa.Boolean(), nullable=False),
    sa.Column('take_profit_roi_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('stop_loss_roi_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('max_open_positions_per_symbol', sa.Integer(), nullable=False),
    sa.Column('daily_max_loss_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('candle_timeframe', sa.String(length=8), nullable=False),
    sa.Column('scan_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('post_trade_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('min_24h_volume_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('long_enabled', sa.Boolean(), nullable=False),
    sa.Column('short_enabled', sa.Boolean(), nullable=False),
    sa.Column('trailing_stop_enabled', sa.Boolean(), nullable=False),
    sa.Column('trailing_stop_activation_roi_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('trailing_stop_callback_rate_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_spread_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_funding_rate_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_volatility_atr_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ema_fast_period', sa.Integer(), nullable=False),
    sa.Column('ema_mid_period', sa.Integer(), nullable=False),
    sa.Column('ema_slow_period', sa.Integer(), nullable=False),
    sa.Column('rsi_period', sa.Integer(), nullable=False),
    sa.Column('atr_period', sa.Integer(), nullable=False),
    sa.Column('rsi_long_min', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rsi_long_max', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rsi_short_min', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rsi_short_max', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume_multiplier_min', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_signal_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('top_n_symbols_by_volume', sa.Integer(), nullable=False),
    sa.Column('working_type', sa.String(length=16), nullable=False),
    sa.Column('min_liquidation_distance_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_slippage_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('paper_taker_commission_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('paper_start_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('paper_funding_simulation_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_settings'))
    )
    op.create_table('daily_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gross_pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_commission_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_funding_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('daily_loss_limit_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_statistics'))
    )
    op.create_index(op.f('ix_daily_statistics_bot_mode'), 'daily_statistics', ['bot_mode'], unique=False)
    op.create_index(op.f('ix_daily_statistics_stat_date'), 'daily_statistics', ['stat_date'], unique=False)
    op.create_table('funding_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('funding_rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('funding_fee_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('funding_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_records'))
    )
    op.create_index(op.f('ix_funding_records_funding_time'), 'funding_records', ['funding_time'], unique=False)
    op.create_index(op.f('ix_funding_records_position_id'), 'funding_records', ['position_id'], unique=False)
    op.create_index(op.f('ix_funding_records_symbol'), 'funding_records', ['symbol'], unique=False)
    op.create_table('order_fills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('binance_trade_id', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission_asset', sa.String(length=16), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_fills'))
    )
    op.create_index(op.f('ix_order_fills_order_id'), 'order_fills', ['order_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=24), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('avg_fill_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('commission_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('client_order_id', sa.String(length=36), nullable=False),
    sa.Column('binance_order_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_binance_order_id'), 'orders', ['binance_order_id'], unique=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_position_id'), 'orders', ['position_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('pnl_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('record_type', sa.String(length=24), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pnl_records'))
    )
    op.create_index(op.f('ix_pnl_records_position_id'), 'pnl_records', ['position_id'], unique=False)
    op.create_index(op.f('ix_pnl_records_recorded_at'), 'pnl_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_pnl_records_trade_id'), 'pnl_records', ['trade_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('binance_position_side', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('margin_type', sa.String(length=16), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('notional_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('break_even_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('roi_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('margin_ratio_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('open_commission_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close_commission_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('funding_fee_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('protective_orders_ok', sa.Boolean(), nullable=False),
    sa.Column('stop_loss_algo_order_id', sa.String(length=36), nullable=True),
    sa.Column('take_profit_algo_order_id', sa.String(length=36), nullable=True),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('open_reason', sa.String(length=255), nullable=True),
    sa.Column('close_reason', sa.String(length=32), nullable=True),
    sa.Column('open_order_id', sa.String(length=36), nullable=True),
    sa.Column('close_order_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index(op.f('ix_positions_signal_id'), 'positions', ['signal_id'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mismatches_found', sa.Integer(), nullable=False),
    sa.Column('external_positions_found', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('entered_safe_mode', sa.Boolean(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_runs'))
    )
    op.create_table('risk_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('bot_mode', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_risk_events_symbol'), 'risk_events', ['symbol'], unique=False)
    op.create_table('strategy_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_result_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resulting_position_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_signals'))
    )
    op.create_index(op.f('ix_strategy_signals_symbol'), 'strategy_signals', ['symbol'], unique=False)
    op.create_table('symbol_rules',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('in_analysis_list', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.String(length=255), nullable=True),
    sa.Column('long_enabled', sa.Boolean(), nullable=False),
    sa.Column('short_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_leverage_override', sa.Integer(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_signal_id', sa.String(length=36), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_symbol_rules'))
    )
    op.create_table('symbols',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('margin_asset', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('contract_type', sa.String(length=24), nullable=False),
    sa.Column('price_tick_size', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('lot_step_size', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('market_lot_step_size', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('max_qty', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('min_notional', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('funding_rate', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('volume_24h_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('open_interest', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('spread_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('market_data_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_symbols'))
    )
    op.create_table('system_health',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_health'))
    )
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('margin_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('notional_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('open_commission_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close_commission_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('funding_fee_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_roi_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('net_roi_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('open_reason', sa.String(length=255), nullable=True),
    sa.Column('close_reason', sa.String(length=32), nullable=False),
    sa.Column('stop_loss_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('binance_order_id_open', sa.String(length=64), nullable=True),
    sa.Column('binance_order_id_close', sa.String(length=64), nullable=True),
    sa.Column('client_order_id_open', sa.String(length=36), nullable=True),
    sa.Column('client_order_id_close', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index(op.f('ix_trades_position_id'), 'trades', ['position_id'], unique=True)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('worker_locks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lock_name', sa.String(length=128), nullable=False),
    sa.Column('holder_id', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_locks'))
    )
    op.create_index(op.f('ix_worker_locks_lock_name'), 'worker_locks', ['lock_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_locks_lock_name'), table_name='worker_locks')
    op.drop_table('worker_locks')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_position_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('system_health')
    op.drop_table('symbols')
    op.drop_table('symbol_rules')
    op.drop_index(op.f('ix_strategy_signals_symbol'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.drop_index(op.f('ix_risk_events_symbol'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_signal_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_pnl_records_trade_id'), table_name='pnl_records')
    op.drop_index(op.f('ix_pnl_records_recorded_at'), table_name='pnl_records')
    op.drop_index(op.f('ix_pnl_records_position_id'), table_name='pnl_records')
    op.drop_table('pnl_records')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_position_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_binance_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_fills_order_id'), table_name='order_fills')
    op.drop_table('order_fills')
    op.drop_index(op.f('ix_funding_records_symbol'), table_name='funding_records')
    op.drop_index(op.f('ix_funding_records_position_id'), table_name='funding_records')
    op.drop_index(op.f('ix_funding_records_funding_time'), table_name='funding_records')
    op.drop_table('funding_records')
    op.drop_index(op.f('ix_daily_statistics_stat_date'), table_name='daily_statistics')
    op.drop_index(op.f('ix_daily_statistics_bot_mode'), table_name='daily_statistics')
    op.drop_table('daily_statistics')
    op.drop_table('bot_settings')
    op.drop_table('bot_runtime_status')
    op.drop_index(op.f('ix_bot_events_event_type'), table_name='bot_events')
    op.drop_table('bot_events')
    op.drop_table('binance_connection_status')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analysis_results_symbol'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_analyzed_at'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_algo_orders_symbol'), table_name='algo_orders')
    op.drop_index(op.f('ix_algo_orders_status'), table_name='algo_orders')
    op.drop_index(op.f('ix_algo_orders_position_id'), table_name='algo_orders')
    op.drop_index(op.f('ix_algo_orders_client_algo_id'), table_name='algo_orders')
    op.drop_index(op.f('ix_algo_orders_binance_order_id'), table_name='algo_orders')
    op.drop_table('algo_orders')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_admin_sessions_token_hash'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_admin_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    # ### end Alembic commands ###
